### ISSUE TITLE
How to receive 0 reward

### ISSUE THREAD

**Issue by rafi16jan** [LonesomeBullBoy/RDR2-Bounties-Expansion-RDR1-Edition#1]
Hello, this is a great mod! Thanks for your work. How can I modify it to give 0$ reward? Should I just edit the [rewards](https://github.com/LonesomeBullBoy/RDR2-Bounties-Expansion-RDR1-Edition/blob/3df5bfb9c7010f66edf3b20032c0b1f03d1b0a2f/src/src/BountyMissionsFactory.cpp#L120)  for each bounty to 0? And how do I compile it to an ASI file?

**Comment by LonesomeBullBoy** [comment]
Yes, just change the data.reward to 0 for each bounty you don't want to receive money from.

To compile it to an .asi file, I take it you're using microsoft visual studio? If so, just click on Build->Build Solution (or Ctrl+Shift+B).  Now in case you get a .dll file just change the data type to .asi that should work too.

I hope this will help you 👍.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by rafi16jan** [comment]
Thanks for your quick response! I see, I'll download VS then. I will let you know if I encounter problems. Thanks again for your work
